### ISSUE TITLE
 Missing access token

### ISSUE THREAD

**Issue by TheBrat** [requests/requests-oauthlib#205]
Hello!
I tried your code 
from requests_oauthlib import OAuth2Session
google = OAuth2Session(r'client_id', token=r'token')
url = 'https://www.googleapis.com/oauth2/v1/userinfo'
r = google.get(url)

Just to see if it is running but I get this error ValueError: Missing access token. I know that token and id are not correct but this error is something else I think?
Thank you

**Comment by Lukasa** [comment]
Can you provide the full traceback, please?

**Comment by TheBrat** [comment]
Traceback (most recent call last):
  File "calltestOauth2.py", line 6, in <module>
    r = google.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 281, in request
    http_method=method, body=data, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 191, in add_token
    raise ValueError("Missing access token.")
ValueError: Missing access token.

**Comment by Lukasa** [comment]
Apologies, I believe the API changed but we failed to update the README. You'd need to populate that with a dictionary including an access token. You may find it more useful to follow the documentation [here](https://requests-oauthlib.readthedocs.org/en/latest/examples/google.html) instead.

**Comment by TheBrat** [comment]
ok thank you!

**Comment by ad-m** [comment]
So, this example isn't correct https://requests-oauthlib.readthedocs.org/en/latest/examples/real_world_example.html ?

**Comment by Lukasa** [comment]
I believe that example is fine.

**Comment by boulderdave** [comment]
@Lukasa seems the example @ad-m is also outdated (uses identical approach @TheBrat was referencing).

It looks like almost all your examples still use this approach, yea?
i.e.: http://requests-oauthlib.readthedocs.io/en/latest/oauth2_workflow.html#web-application-flow

I'm actually finding it difficult to find any working examples that allow me to request resources by simply providing the token upon initialization of the oauth session, rather than passing in the key, secret, redirect_uri, etc. and requesting the token in real time.  

I need to request resources via a cron job - so using a pre-existing token is required.  Your outdated examples demonstrated that. 
Any help is greatly appreciated.  
```
google = OAuth2Session(client_id, scope=scope, redirect_uri=redirect_uri)
```

**Comment by boulderdave** [comment]
This is helpful actually - seems to be just what I'm needing.  
https://github.com/requests/requests-oauthlib/blob/master/tests/test_oauth2_session.py#L39
