### ISSUE TITLE
Client_id and client_secret get duplicated in fetch_token()

### ISSUE THREAD

**Issue by tuukkamustonen** [requests/requests-oauthlib#249]
After #229, passing `client_id` & `client_secret` in `fetch_token()` duplicates them into both request body and as basic auth headers, causing following error at least on PingFederate (a commercial OAuth2 server):

    oauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client) The client MUST NOT use more than one authentication method in each request.

Shouldn't the library omit the fields from request body, if they are injected as HTTP Basic auth header?

**Comment by Lukasa** [comment]
So I'm not surprised we have a problem here, but the issue seems to boil down to the fact that no two OAuth2 providers seem to agree on how they want auth passed to them. If you look through the issues on this repo, there is stunning inconsistency across the lot of them as to whether they accept Basic, body-only, both, or either but only one. It's simply not possible to automatically get this right for all implementations.

Generally speaking, then, the MUST NOT being referred to in this case is not actually being enforced across most OAuth implementations. For that reason, I'm inclined to want to keep the current behaviour at this time.

However, you can force us to not send the Basic auth header by setting `auth=False` when you call `fetch_token`. That should resolve your issue.

**Comment by tuukkamustonen** [comment]
Alright, thanks for the quick reply!

So, to summarize solutions:

1) To send only basic auth headers: `auth=HTTPBasicAuth('...', '...')`
2) To send only as body: `auth=False, client_id='...', client_secret='...'`
3) To send as both: `client_id='...', client_secret='...'`

Sending both as default feels a bit weird to me, but I do understand the obscurity of the spec and pains in making the lib work for everyone. This is fine.

**Comment by Lukasa** [comment]
Thanks for your understanding @tuukkamustonen! I have to admit a personal loathing for the OAuth 2 spec: it seems to allow basically anything, which means writing one library that interoperates with everything is absurdly tricky. =( I agree that the default behaviour is kinda crazy, but right now it seems to have the highest success rate: if only for the terrible reason that no-one is enforcing the spec!
